<?
$TITLE = [
	// Studio Ghibli
	["FtB: Castle in the Sky","Laputa: Castle in the Sky"],
	["Grave of the Beats","Grave of the Fireflies"],
	["My Neighbor XceeD","My Neighbor Totoro"],
	["XceeD's Delivery Service","Kiki's Delivery Service"],
	["FtB Yesterday","Only Yesterday"],
	["Nejuer Rosso","Porco Rosso"],
	["FtB Poko","Pom Poko"],
	["Whisper of the Nejuer","Whisper of the Heart"],
	["FtB Mononoke","Princess Mononoke"],
	["My Neighbors the XceeDs","My Neighbors the Yamadas"],
	["Spirited FtB","Spirited Away"],
	["XceeD's Cat Returns","The Cat Returns"],
	["XceeD's Moving Castle","Howl's Moving Castle"],
	["Tales from FtB","Tales from Earthsea"],
	["XceeD on the Cliff by the Sea","Ponyo on the Cliff by the Sea"],
	["The Secret World of Xceed","The Secret World of Arrietty"],
	["From Up on FtB Hill","From Up on Poppy Hill"],
	["The Beat Rises","The Wind Rises"],
	["The Tale of the Princess Nejuer","The Tale of the Princess Kaguya"],
	["When XceeD Was There","When Marnie Was There"],
	["I Can Feel the Beats","I Can Hear the Sea"],
	
	// Western Films
	["FtB and FtBility","Sense and Sensibility"],
	["The Grand XceeD Hotel","The Grand Budapest Hotel"],
	["Saving FtB","Saving Private Ryan"],
	["The Good, the Bad and the Nejuer","The Good, the Bad and the Ugly"],
	
	// Games
	["FtB6 : the Embodiment of Scarlet Nejuer.","the Embodiment of Scarlet Devil."],
	
	// Anime
	["FtB! Euphonium","Sound! Euphonium"],
	["F - a Tale of Beats.","ef - a tale of memories."],
	["Tengen Toppa XceeD Nejuer","Tengen Toppa Gurren Lagann"],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
	["",""],
];
?>